Repository Code-4-Community/jpal-backend, pull requests merged in 2022-01, with the labels that each got.

#35 Add port to .env file
  example.env
  src/main.ts
Labels: size/xs

#29 Create PATCH /survey
  src/assignment/types/assignment.entity.ts
  src/reviewer/types/reviewer.entity.ts
  src/survey/dto/create-batch-assignments.dto.ts
  src/survey/survey.controller.ts
  src/survey/survey.module.ts
  src/survey/survey.service.spec.ts
  src/survey/survey.service.ts
  src/youth/types/youth.entity.ts
  test/db/MockRepository.ts
  test/e2e/survey.e2e-spec.ts
Labels: size/m

#36 Added create:migration to npm scripts
  README.md
  package.json
Labels: size/xs

#38 Upgrade pact packages to work with M1 mac
  package-lock.json
  package.json
Labels: size/xl
