Repository Code-4-Community/jpal-backend, pull requests merged in 2022-02, with the labels that each got.

#39 add api docs link to README.md
  README.md
Labels: size/xs

#40 add date to survey
  migrations/1644181216652-add date to survey.ts
  package-lock.json
  src/survey/mockSurveyService.ts
  src/survey/survey.controller.spec.ts
  src/survey/survey.service.spec.ts
  src/survey/types/survey.entity.ts
  test/e2e/survey.e2e-spec.ts
Labels: size/s

#34 get survey for reviewer endpoint
  src/survey/dto/survey-assignment.dto.ts
  src/survey/mockSurveyService.ts
  src/survey/survey.controller.spec.ts
  src/survey/survey.controller.ts
  src/survey/survey.service.spec.ts
  src/survey/survey.service.ts
  src/survey/types/survey.entity.ts
  src/surveyTemplate/types/surveyTemplate.entity.ts
  src/user/user.service.spec.ts
  test/e2e/survey.e2e-spec.ts
Labels: size/m

#45 Survey Service Error Handling
  package-lock.json
  src/survey/survey.service.spec.ts
  src/survey/survey.service.ts
Labels: size/s
